
- name: install nginx httpd-tools
  yum: 
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
     - epel-release
     - nginx
     - httpd-tools

- name: Add entries in nginx config file
  blockinfile: 
    path: /etc/network/interfaces 
    backup: yes
    block: |
        content="server {
        listen 80;
        server_name your_domain.com;
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/htpasswd.kibana;
 
        location / {
        proxy_pass http://localhost:5601;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        }
        }

- name: Add a user to a password file and ensure permissions are set
  htpasswd:
    path: /etc/nginx/htpasswd.kibana
    name: admin
    password: 'Bokt123&'
    owner: root
    group: www-data
    mode: 0640


- name: Add Nginx to run at the boot time and start Nginx
  systemd:
    name: nginx         
    state: started
    enabled: yes
