- hosts: otdservers
  user: oracle
  become: yes
  roles:
    - gen-dependencies
    - package-update
    - create-group
    - create-user
    - smb-packages 
#    - create-user2
#    - create-user3
    
