---
# tasks file for create-user3
- name: Create user
  user: name=user shell=/bin/bash home=/home/oracle groups=oinstall,jenkins generate_ssh_key=yes ssh_key_bits=2048
- name: Set password to oracle
  shell: echo oracle:Kala8Kuta | sudo chpasswd
  no_log: True



























